"""
annotation_app/app.py

Streamlit pairwise preference annotation tool for DiaLLM generation evaluation.

Annotators compare responses from Llama dialect models and judge which sounds
more natural for their target dialect. Results are saved to a local CSV.

Run:
    streamlit run annotation_app/app.py
"""

import json
import random
import csv
import os
from pathlib import Path
from datetime import datetime

import streamlit as st

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
RESPONSES_FILE = Path(__file__).parent.parent / "annotation_responses.jsonl"
FAMILY = "llama"
STAGE_ORDER = ["sft", "dpo", "grpo", "gspo"]
COMPARISONS = [
    ("sft", "dpo"),
    ("sft", "grpo"),
    ("sft", "gspo"),
    ("grpo", "gspo"),
]
DIALECTS = {
    "en-AU": "aus",
    "en-IN": "ind",
    "en-UK": "brit",
}
SEED = 42

INSTRUCTIONS = """
### Instructions

You will see **25 pairs of responses** to the same prompt, each pair generated by a different model.
Your task is to judge **which response sounds more natural and authentic for your assigned dialect**.

- Read both responses carefully.
- Select **A**, **B**, or **Tie** — whichever response feels more like fluent, natural {dialect} English.
- There are no right or wrong answers; go with your instinct.
- You cannot go back to change a previous answer, so take your time on each pair.

Your responses will be saved to a CSV file at the end. Please send this file back once complete.
"""

# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------
@st.cache_data
def load_responses():
    records = []
    with open(RESPONSES_FILE, encoding="utf-8") as f:
        for line in f:
            records.append(json.loads(line))
    return records


def build_pairs(records, dialect_code, seed=SEED):
    """
    Build 100 randomised pairs for a given dialect (variant code e.g. 'aus').
    Each pair: (prompt_id, prompt_text, domain, stage_a, stage_b, response_a, response_b, a_is_left)
    a_is_left: whether stage_a appears on the left (randomised).
    """
    rng = random.Random(seed)

    # Index by (stage, prompt_id)
    idx = {}
    for r in records:
        if r["family"] == FAMILY and r["variant"] == dialect_code:
            idx[(r["stage"], r["prompt_id"])] = r

    # Collect prompt metadata from SFT records (always present)
    prompts = sorted(
        [r for r in records if r["family"] == FAMILY and r["variant"] == dialect_code and r["stage"] == "sft"],
        key=lambda r: r["prompt_id"],
    )

    pairs = []
    for prompt_rec in prompts:
        pid = prompt_rec["prompt_id"]
        for stage_a, stage_b in COMPARISONS:
            rec_a = idx.get((stage_a, pid))
            rec_b = idx.get((stage_b, pid))
            if rec_a is None or rec_b is None:
                continue
            a_is_left = rng.random() < 0.5
            if a_is_left:
                left, right = rec_a, rec_b
                left_stage, right_stage = stage_a, stage_b
            else:
                left, right = rec_b, rec_a
                left_stage, right_stage = stage_b, stage_a

            pairs.append({
                "prompt_id":    pid,
                "domain":       prompt_rec["domain"],
                "prompt":       prompt_rec["prompt"],
                "stage_a":      stage_a,
                "stage_b":      stage_b,
                "left_stage":   left_stage,
                "right_stage":  right_stage,
                "left_resp":    left["response"],
                "right_resp":   right["response"],
                "a_is_left":    a_is_left,
            })

    return pairs


# ---------------------------------------------------------------------------
# CSV saving
# ---------------------------------------------------------------------------
def save_results(annotator_name, dialect, pairs, judgements):
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_name = annotator_name.strip().replace(" ", "_")
    filename = f"annotations_{dialect}_{safe_name}_{timestamp}.csv"

    fieldnames = [
        "annotator", "dialect", "prompt_id", "domain", "comparison",
        "stage_a", "stage_b", "a_is_left", "judgement", "winner_stage",
    ]
    with open(filename, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for pair, judgement in zip(pairs, judgements):
            if judgement == "A":
                winner = pair["stage_a"]
            elif judgement == "B":
                winner = pair["stage_b"]
            else:
                winner = "tie"
            writer.writerow({
                "annotator":   annotator_name,
                "dialect":     dialect,
                "prompt_id":   pair["prompt_id"],
                "domain":      pair["domain"],
                "comparison":  f"{pair['stage_a']}_vs_{pair['stage_b']}",
                "stage_a":     pair["stage_a"],
                "stage_b":     pair["stage_b"],
                "a_is_left":   pair["a_is_left"],
                "judgement":   judgement,
                "winner_stage": winner,
            })

    return filename


# ---------------------------------------------------------------------------
# App
# ---------------------------------------------------------------------------
def main():
    st.set_page_config(page_title="DiaLLM Annotation", layout="wide")
    st.title("DiaLLM — Dialect Generation Preference Annotation")

    # --- Setup screen ---
    if "started" not in st.session_state:
        st.markdown("## Setup")
        name = st.text_input("Your name", placeholder="e.g. Jane Smith")
        dialect = st.selectbox("Your assigned dialect", list(DIALECTS.keys()))
        if st.button("Start annotation", disabled=not name.strip()):
            st.session_state.started       = True
            st.session_state.annotator     = name.strip()
            st.session_state.dialect       = dialect
            st.session_state.dialect_code  = DIALECTS[dialect]
            records = load_responses()
            st.session_state.pairs         = build_pairs(records, DIALECTS[dialect])
            st.session_state.current       = 0
            st.session_state.judgements    = []
            st.rerun()
        return

    # --- Annotation complete screen ---
    pairs      = st.session_state.pairs
    current    = st.session_state.current
    total      = len(pairs)
    dialect    = st.session_state.dialect
    annotator  = st.session_state.annotator

    if current >= total:
        st.success(f"All {total} pairs complete — thank you, {annotator}!")
        filename = save_results(annotator, dialect, pairs, st.session_state.judgements)
        st.info(f"Results saved to **{filename}**. Please send this file back.")
        with open(filename, "rb") as f:
            st.download_button("Download CSV", f, file_name=filename, mime="text/csv")
        return

    # --- Progress ---
    st.progress(current / total, text=f"Pair {current + 1} of {total}")

    # --- Instructions (collapsible after first pair) ---
    with st.expander("Instructions", expanded=(current == 0)):
        st.markdown(INSTRUCTIONS.format(dialect=dialect))

    # --- Current pair ---
    pair = pairs[current]
    st.markdown(f"**Domain:** {pair['domain'].replace('_', ' ').title()}")
    st.markdown(f"**Prompt:** {pair['prompt']}")
    st.markdown("---")

    col_a, col_b = st.columns(2)
    with col_a:
        st.markdown("### Response A")
        st.markdown(pair["left_resp"])
    with col_b:
        st.markdown("### Response B")
        st.markdown(pair["right_resp"])

    st.markdown("---")
    st.markdown("**Which response sounds more natural for {} English?**".format(dialect))

    col1, col2, col3 = st.columns(3)
    with col1:
        if st.button("A", use_container_width=True):
            # Map left/right back to A/B (A = stage_a)
            judgement = "A" if pair["a_is_left"] else "B"
            st.session_state.judgements.append(judgement)
            st.session_state.current += 1
            st.rerun()
    with col2:
        if st.button("Tie", use_container_width=True):
            st.session_state.judgements.append("Tie")
            st.session_state.current += 1
            st.rerun()
    with col3:
        if st.button("B", use_container_width=True):
            judgement = "B" if pair["a_is_left"] else "A"
            st.session_state.judgements.append(judgement)
            st.session_state.current += 1
            st.rerun()


if __name__ == "__main__":
    main()
